endpoint: "opc.tcp://192.168.137.1:4840"
namespace_index: 3

nodes:
  status:   '"ROS2_COMM"."STATUS"'
  mode:     '"ROS2_COMM"."MODE"'
  command:  '"ROS2_COMM"."COMMAND"'
  speed:    '"ROS2_COMM"."SPEED"'
  slider1:  '"ROS2_COMM"."GO_TO_POS_1"'
  slider2:  '"ROS2_COMM"."GO_TO_POS_2"'

structs:
  mod_root:  '"ROS2_COMM"."MOD"'
  stat_root: '"ROS2_COMM"."STAT"'
  sensing_root: '"ROS2_COMM"."STAT"."Robot_Sensing_Status"'
  cleaning_root: '"ROS2_COMM"."STAT"."Robot_Cleaning_Status"'
  spot1_spatter_classes:
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_1_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_1_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_2_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_3_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_4_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_5_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_6_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_7_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_8_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_9_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_10_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_11_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M1"."Spot_12_Spatter_Class"'
  
  spot2_spatter_classes:
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_1_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_2_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_3_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_4_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_5_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_6_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_7_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_8_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_9_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_10_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_11_Spatter_Class"'
      - '"ROS2_COMM"."STAT"."Spot_M2"."Spot_12_Spatter_Class"' 

  Workcell: '"ROS2_COMM"."MOD"."Workcell_Status"'
  discover:  false
  mod_fields: ["STARTUP","CALIBRATION","LEARNING","MAINTENANCE","EMERGENCY","COBOT","FULLY_AUTOMATIC","SHUTDOWN_MODE"]
  stat_fields: ["STARTUP","CALIBRATION","LEARNING","MAINTENANCE","EMERGENCY","COBOT"]


timing:
  sampling_ms: 50
  write_timeout_ms: 200
  reconnect: { initial_ms: 500, max_ms: 10000, multiplier: 2.0 }
