cobot1:
  robot_name: "sensing_cobot"
  sensing_joint_states: "/sr/xbotcore/joint_states"
  sensing_service: "/sr/xbotcore/homing/switch" 
  home_position: [0.0036, 0.6, 1.57, 0.003, 0.99, 0,005]
  target_position: [0.002013,-0.53907,-1.23233,1.57542,1.38901,-0.00119]

cobot2: 
  robot_name: "cleaning_cobot"
  cleaning_joint_states: "/cr/xbotcore/joint_states"
  cleaning_service: "/cr/xbotcore/homing/switch"
  home_position: [1.4543,-0.4016,0.8603,0.0024,1.1211,-3.6882]
  
