cobot1:
  robot_name: "sensing_cobot"
  sensing_joint_states: "/sensing/joint_states"
  sensing_service: "/sensing/go_home" 
  home_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0,0]

cobot2: 
  robot_name: "cleaning_cobot"
  cleaning_joint_states: "/cleaning/joint_states"
  cleaning_service: "/cleaning/go_home"
  home_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0,0]
